// Yonodex Desktop Client - Match (Trade) struct
// Whitepaper Layer 5, Section 7.3: Matching Engine
//
// A Match represents an agreed trade between a buyer and seller. Both parties
// must sign the match before it proceeds to settlement (Phase 2.C).
//
// Lifecycle:
//   1. Matching engine finds a crossing pair in the local order book
//   2. One node proposes the match (with its signature)
//   3. Counterparty verifies against their local book, adds their signature
//   4. Signed match is broadcast — both orders tombstoned as Filled
//   5. (Phase 2.C) Settlement occurs on-chain via 2-of-2 multisig escrow

use crate::clock::VectorClock;
use serde::{Deserialize, Serialize};

/// A proposed or confirmed trade between two orders.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Trade {
    /// Unique trade identifier (client-generated by the proposing node).
    pub id: String,

    /// The buy-side order id.
    pub buy_order_id: String,

    /// The sell-side order id.
    pub sell_order_id: String,

    /// Ed25519 public key of the buyer (from the buy order's owner field).
    pub buyer_owner: String,

    /// Ed25519 public key of the seller (from the sell order's owner field).
    pub seller_owner: String,

    /// Execution price (matches the resting order's price).
    pub price: String,

    /// Execution amount (min of the two orders' remaining amounts).
    pub amount: String,

    /// Trading pair.
    pub pair: String,

    /// Buyer's signature over signable_bytes() — empty until signed.
    pub buyer_signature: String,

    /// Seller's signature over signable_bytes() — empty until signed.
    pub seller_signature: String,

    /// Vector clock at the moment of proposal.
    pub vector_clock: VectorClock,

    /// Unix timestamp (seconds) when the match was proposed.
    pub created_at: i64,
}

impl Trade {
    /// The canonical byte sequence that both parties sign.
    ///
    /// Deterministic order of fields so both peers hash identical bytes.
    /// Signatures are excluded (they'd be circular).
    pub fn signable_bytes(&self) -> Vec<u8> {
        let mut s = String::new();
        s.push_str(&self.id);
        s.push('|');
        s.push_str(&self.buy_order_id);
        s.push('|');
        s.push_str(&self.sell_order_id);
        s.push('|');
        s.push_str(&self.buyer_owner);
        s.push('|');
        s.push_str(&self.seller_owner);
        s.push('|');
        s.push_str(&self.price);
        s.push('|');
        s.push_str(&self.amount);
        s.push('|');
        s.push_str(&self.pair);
        s.push('|');
        s.push_str(&self.created_at.to_string());
        s.push('|');

        // Vector clock — sorted for determinism
        let mut keys: Vec<_> = self.vector_clock.keys().cloned().collect();
        keys.sort();
        for k in keys {
            s.push_str(&k);
            s.push(':');
            s.push_str(&self.vector_clock[&k].to_string());
            s.push(',');
        }

        s.into_bytes()
    }
}

// ---- Signing ----
// Whitepaper Layer 5, Section 7.3: both parties sign the trade agreement.
// Each signer only signs bytes they agree with — nothing else.

use ed25519_dalek::{Signature, Signer, SigningKey, Verifier, VerifyingKey};

/// Sign the trade on behalf of `signer_owner`.
///
/// If signer_owner == trade.buyer_owner → fills buyer_signature.
/// If signer_owner == trade.seller_owner → fills seller_signature.
/// Any other value is an error.
pub fn sign_as(
    trade: &Trade,
    signing_key: &SigningKey,
    signer_owner: &str,
) -> Result<Trade, String> {
    let mut signed = trade.clone();
    let bytes = signed.signable_bytes();
    let signature = signing_key.sign(&bytes);
    let sig_hex = hex::encode(signature.to_bytes());

    if signer_owner == signed.buyer_owner {
        signed.buyer_signature = sig_hex;
    } else if signer_owner == signed.seller_owner {
        signed.seller_signature = sig_hex;
    } else {
        return Err(format!(
            "signer {} is not buyer {} or seller {}",
            signer_owner, signed.buyer_owner, signed.seller_owner
        ));
    }

    Ok(signed)
}

/// Verify the buyer's signature on a trade.
pub fn verify_buyer_signature(trade: &Trade) -> Result<(), String> {
    verify_one(trade, &trade.buyer_owner, &trade.buyer_signature, "buyer")
}

/// Verify the seller's signature on a trade.
pub fn verify_seller_signature(trade: &Trade) -> Result<(), String> {
    verify_one(trade, &trade.seller_owner, &trade.seller_signature, "seller")
}

/// Verify both signatures. Used before settlement.
pub fn verify_both_signatures(trade: &Trade) -> Result<(), String> {
    verify_buyer_signature(trade)?;
    verify_seller_signature(trade)?;
    Ok(())
}

/// Check that both signature fields are present (may not be verified).
pub fn is_fully_signed(trade: &Trade) -> bool {
    !trade.buyer_signature.is_empty() && !trade.seller_signature.is_empty()
}

fn verify_one(
    trade: &Trade,
    owner_hex: &str,
    sig_hex: &str,
    label: &str,
) -> Result<(), String> {
    if sig_hex.is_empty() {
        return Err(format!("{label} signature is empty"));
    }

    // Decode owner public key
    let owner_bytes = hex::decode(owner_hex)
        .map_err(|e| format!("invalid {label} owner hex: {e}"))?;
    if owner_bytes.len() != 32 {
        return Err(format!(
            "{label} owner must be 32 bytes, got {}",
            owner_bytes.len()
        ));
    }
    let mut owner_arr = [0u8; 32];
    owner_arr.copy_from_slice(&owner_bytes);
    let verifying_key = VerifyingKey::from_bytes(&owner_arr)
        .map_err(|e| format!("invalid {label} public key: {e}"))?;

    // Decode signature
    let sig_bytes = hex::decode(sig_hex)
        .map_err(|e| format!("invalid {label} signature hex: {e}"))?;
    if sig_bytes.len() != 64 {
        return Err(format!(
            "{label} signature must be 64 bytes, got {}",
            sig_bytes.len()
        ));
    }
    let mut sig_arr = [0u8; 64];
    sig_arr.copy_from_slice(&sig_bytes);
    let signature = Signature::from_bytes(&sig_arr);

    // Verify against canonical bytes
    let bytes = trade.signable_bytes();
    verifying_key
        .verify(&bytes, &signature)
        .map_err(|e| format!("{label} signature verification failed: {e}"))
}